# Generated by Django 5.2.3 on 2025-06-30 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='Enter a valid phone number starting with 07 or 01', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must start with 07 or 01 and be exactly 10 digits.', regex='^(07|01)\\d{8}$')]),
        ),
    ]
