# Generated by Django 5.2.3 on 2025-06-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_tag_photo_slug_photocategory_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='visible_to_clients',
            field=models.BooleanField(default=True),
        ),
    ]
