# Generated by Django 5.2.3 on 2025-06-19 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_photo_visible_to_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='visible_to_clients',
        ),
    ]
